packages:
  - .
autoInstallPeers: true
configDependencies:
  "@savvy-web/pnpm-plugin-silk": 0.16.0+sha512-YAR8EBaL5r6Rja/X3kJXRq5dCFYVHMegGSsIcqXXjEA8l0J6E+tV7IHJntzVS0SrXZqWpblCEkNCmzkG05Ajug==
loglevel: info
